### ISSUE TITLE
Google Sync doesn't work anymore

### ISSUE THREAD

**Issue by havhav31** [ulangi/ulangi#159]
As I try to sync Ulangi with Google Sheets, I can't login because I encounter with an error. Also when I try to open ulangi.com it says "This website is not secure". I know that the developer has not updating the app but at least there should be a chance to sync. Please, man. I am a heavy Ulangi user and I let all my friends know about the app. I don't want to find another flashcard app. 

```
Login failed. Please see the error below.
ScriptError: Exception: SSL error https://ulangi.com/api/v1/sign-in
```

**Comment by Aisha-K** [comment]
The cards are also not not syncing, and I couldn't get translations because it throws a "Network Error" message. I logged out and uninstalled and reinstalled the app to try to see if it fixes it, but now I'm locked out because it throws the same error when I try to log into my account. I think the server might be down

**Comment by m4drat** [comment]
Besides synchronization and translation, "discover" feature also doesn't work.
As far as I can tell, only certificate update is required to fix the issues.
Please, don't let the best flashcards app die :(

**Comment by udy929** [comment]
Joining the plea. Truly the best flashcards app out there.(

**Comment by jimmyloi** [comment]
The issue has been fixed. Thanks guys!
